In [67]:
import numpy as np

print('''\n1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.''')
print('''answer:''')
a = np.arange(1, 11)
print(a)
a = np.linspace(1, 10, num=10)
print(a)

print('''\n2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.''')
print('''answer:''')
a = np.zeros((3,3), dtype=int)
print(a)

print('''\n3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.''')
print('''answer:''')
a = np.random.randint(1, 11, size=(25)).reshape((5,5))
print(a)
a = np.random.randint(1, 11, size=(5,5))
print(a)

print('''\n4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.''')
print('''answer:''')
a = np.random.random((4,4))
print(a)

print('''\n5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.''')
print('''answer:''')
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
print(f"a = {a}")
print(f"b = {b}")
print("sum =", a + b)
print("subtraction =", a - b)
print("multiplication =", a * b)

print('''\n6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.''')
print('''answer:''')
a = np.random.randint(1, 11, size=7)
b = np.random.randint(1, 11, size=7)
print(f"a = {a}")
print(f"b = {b}")
c = np.dot(a, b)
print("scalar product =", c)

print('''\n7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.''')
print('''answer:''')
a = np.random.randint(1, 11, size=4).reshape(2,2)
b = np.random.randint(1, 11, size=6).reshape(2,3)
print(f"a: \n{a}")
print(f"b: \n{b}")
c = np.dot(a, b)
print("answer:\n", c)

print('''\n8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.''')
print('''answer:''')
a = np.random.randint(1, 11, size=9).reshape(3,3)
print(f"a: \n{a}")
b = np.linalg.inv(a)
print("inverse matrix:\n", b)

c = np.dot(a, b)
print("check:\n", np.rint(c))

print('''\n9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її''')
print('''answer:''')
a = np.random.rand(4, 4)
print(f"a: \n{a}")
b = a.T
print("transposed matrix:\n", b)

print('''\n10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.''')
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
print(f"a: \n{a}")
print(f"b: \n{b}")
c = np.dot(a, b)
print("answer a⋅b:  \n", c)


print('''\n11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.''')
a = np.random.rand(2,3)
b = np.random.rand(3)
print(f"a: \n{a}")
print(f"b: \n{b}")
c = np.dot(a, b)
print("answer a⋅b:  \n", c)

print('''\n12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.''')
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(f"a: \n{a}")
print(f"b: \n{b}")
c = a * b
print("answer a*b:  \n", c)

print('''\n13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.''')
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(f"a: \n{a}")
print(f"b: \n{b}")
c = np.dot(a, b)
print("answer a⋅b:  \n", c)

print('''\n14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.''')
a = np.random.randint(1, 101, size=(5, 5))
print(f"a: \n{a}")
print("sum of matrix elements:\n", a.sum())


print('''\n15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.''')
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print(f"a: \n{a}")
print(f"b: \n{b}")
c = a - b
print("answer a-b:  \n", c)

print('''\n16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.''')
a = np.random.rand(3, 3)
print(f"a: \n{a}")
b = np.array([[a[0, :].sum()],[a[1, :].sum()], [a[2, :].sum()]])
print("answer 1:  \n", b)
c = np.array([[el.sum()] for el in a[:]])
print("answer 2:  \n", c)
d = np.sum(a, axis=1).reshape((3, 1))
print("answer 3:  \n", d)

print('''\n17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.''')
a = np.random.randint(1, 11, size=(3, 4))
print(f"a: \n{a}")
b = np.square(a)
print("answer:  \n", b)
c = a * a
print("answer 2:  \n", c)
d = a ** 2
print("answer 3:  \n", d)

print('''\n18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.''')
a = np.random.randint(1, 51, size=4)
print(f"a: \n{a}")
b = a ** 0.5
print("answer:  \n", b)
c = np.sqrt(a)
print("answer 2:  \n", c)


1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
answer:
[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
answer:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
answer:
[[ 9 10  3 10  7]
 [ 9  3  6  8  6]
 [10  2  4 10  9]
 [ 1  3  2  9  6]
 [ 1  2  7  1  9]]
[[ 7  2  4  6 10]
 [ 4  4  8  3  9]
 [ 6  8  2  8  9]
 [ 8  2  7  8  6]
 [ 8  9  1  8  2]]

4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
answer:
[[0.98271006 0.96488304 0.8251909  0.57375699]
 [0.24825924 0.79237164 0.27742225 0.17225958]
 [0.37573742 0.21263988 0.13022895 0.91942952]
 [0.4030751  0.88638579 0.01129644 0.80611956]]

5 Створіть два одновимірних масиви р