In [88]:
import numpy as np

print('''\n1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.''')
print('''answer:''')
a = np.arange(1, 11)
print(a)
a = np.linspace(1, 10, num=10)
print(a)



1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
answer:
[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [68]:
print('''\n2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.''')
print('''answer:''')
a = np.zeros((3,3), dtype=int)
print(a)


2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
answer:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [70]:
print('''\n3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.''')
print('''answer:''')
a = np.random.randint(1, 11, size=(25)).reshape((5,5))
print(a)
print('''answer 2:''')
a = np.random.randint(1, 11, size=(5,5))
print(a)


3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
answer:
[[ 1  8  3  7  1]
 [ 6  9  7  3  4]
 [ 4  3  7 10  4]
 [ 5  4  7  1  7]
 [ 9  9  7  6  9]]
answer 2:
[[ 9  9  8  3  3]
 [ 3  5  2  4 10]
 [ 2 10  1  1  3]
 [ 3  5  3  9  2]
 [ 3  1 10  7  8]]


In [72]:
print('''\n4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.''')
print('''answer:''')
a = np.random.random((4,4))
print(a)


4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
answer:
[[0.45363908 0.76069776 0.59393941 0.207253  ]
 [0.16191214 0.1797345  0.02805861 0.13623276]
 [0.50229884 0.56283387 0.5784271  0.87937174]
 [0.63421067 0.57745358 0.52196041 0.34858271]]


In [73]:
print('''\n5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.''')
print('''answer:''')
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
print(f"a = {a}")
print(f"b = {b}")
print("sum =", a + b)
print("subtraction =", a - b)
print("multiplication =", a * b)


5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
answer:
a = [ 2  1 10  3  8]
b = [10  6  4  3  4]
sum = [12  7 14  6 12]
subtraction = [-8 -5  6  0  4]
multiplication = [20  6 40  9 32]


In [74]:
print('''\n6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.''')
print('''answer:''')
a = np.random.randint(1, 11, size=7)
b = np.random.randint(1, 11, size=7)
print(f"a = {a}")
print(f"b = {b}")
c = np.dot(a, b)
print("scalar product =", c)


6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
answer:
a = [ 2  9  6 10  4  3  3]
b = [ 3  1  4  6  8 10  9]
scalar product = 188


In [76]:
print('''\n7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.''')
print('''answer:''')
a = np.random.randint(1, 11, size=4).reshape(2,2)
b = np.random.randint(1, 11, size=6).reshape(2,3)
print(f"a: \n{a}")
print(f"b: \n{b}")
c = np.dot(a, b)
print("answer:\n", c)


7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
answer:
a: 
[[10  8]
 [ 3  3]]
b: 
[[10  3  7]
 [ 1  4  1]]
answer:
 [[108  62  78]
 [ 33  21  24]]


In [77]:
print('''\n8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.''')
print('''answer:''')
a = np.random.randint(1, 11, size=9).reshape(3,3)
print(f"a: \n{a}")
b = np.linalg.inv(a)
print("inverse matrix:\n", b)

c = np.dot(a, b)
print("check:\n", np.rint(c))


8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
answer:
a: 
[[ 9  6  9]
 [ 2  5  7]
 [10  9  8]]
inverse matrix:
 [[ 0.13450292 -0.19298246  0.01754386]
 [-0.31578947  0.10526316  0.26315789]
 [ 0.1871345   0.12280702 -0.19298246]]
check:
 [[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


In [78]:
print('''\n9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її''')
print('''answer:''')
a = np.random.rand(4, 4)
print(f"a: \n{a}")
b = a.T
print("transposed matrix:\n", b)


9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її
answer:
a: 
[[0.68237483 0.0012284  0.91024062 0.21414953]
 [0.83016416 0.73546264 0.19298117 0.52314219]
 [0.19266027 0.12953569 0.02954023 0.4141927 ]
 [0.59070371 0.45744288 0.6918194  0.71763105]]
transposed matrix:
 [[0.68237483 0.83016416 0.19266027 0.59070371]
 [0.0012284  0.73546264 0.12953569 0.45744288]
 [0.91024062 0.19298117 0.02954023 0.6918194 ]
 [0.21414953 0.52314219 0.4141927  0.71763105]]


In [79]:
print('''\n10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.''')
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
print(f"a: \n{a}")
print(f"b: \n{b}")
c = np.dot(a, b)
print("answer a⋅b:  \n", c)


10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
a: 
[[ 7  4  1  3]
 [ 2 10  2  9]
 [ 8  4  8  9]]
b: 
[10  7  2  3]
answer a⋅b:  
 [109 121 151]


In [80]:
print('''\n11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.''')
a = np.random.rand(2,3)
b = np.random.rand(3)
print(f"a: \n{a}")
print(f"b: \n{b}")
c = np.dot(a, b)
print("answer a⋅b:  \n", c)


11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
a: 
[[0.57781116 0.56584215 0.05974498]
 [0.95682098 0.9060917  0.95387954]]
b: 
[0.86329091 0.2657549  0.23212802]
answer a⋅b:  
 [0.66306292 1.28823533]


In [82]:
print('''\n12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.''')
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(f"a: \n{a}")
print(f"b: \n{b}")
c = a * b
print("answer a*b:  \n", c)


12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
a: 
[[2 5]
 [3 6]]
b: 
[[4 9]
 [9 4]]
answer a*b:  
 [[ 8 45]
 [27 24]]


In [83]:
print('''\n13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.''')
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(f"a: \n{a}")
print(f"b: \n{b}")
c = np.dot(a, b)
print("answer a⋅b:  \n", c)


13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
a: 
[[3 2]
 [1 7]]
b: 
[[5 5]
 [9 7]]
answer a⋅b:  
 [[33 29]
 [68 54]]


In [84]:
print('''\n14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.''')
a = np.random.randint(1, 101, size=(5, 5))
print(f"a: \n{a}")
print("sum of matrix elements:\n", a.sum())


14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
a: 
[[35 62 44 57 30]
 [41 69 47 77 67]
 [94 76 37 83 55]
 [ 9 57 28 51 28]
 [ 1 33 70 92 58]]
sum of matrix elements:
 1301


In [85]:
print('''\n15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.''')
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print(f"a: \n{a}")
print(f"b: \n{b}")
c = a - b
print("answer a-b:  \n", c)


15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
a: 
[[ 7  5  1  5]
 [ 5  8  2  5]
 [ 8  1  9  8]
 [ 7  2 10  6]]
b: 
[[ 1  3 10  2]
 [ 2  8  7  7]
 [ 1  6  7  6]
 [ 8  1  2  8]]
answer a-b:  
 [[ 6  2 -9  3]
 [ 3  0 -5 -2]
 [ 7 -5  2  2]
 [-1  1  8 -2]]


In [86]:
print('''\n16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.''')
a = np.random.rand(3, 3)
print(f"a: \n{a}")
b = np.array([[a[0, :].sum()],[a[1, :].sum()], [a[2, :].sum()]])
print("answer 1:  \n", b)
c = np.array([[el.sum()] for el in a[:]])
print("answer 2:  \n", c)
d = np.sum(a, axis=1).reshape((3, 1))
print("answer 3:  \n", d)


16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
a: 
[[0.00307499 0.99515228 0.14616436]
 [0.84048609 0.42454848 0.07792819]
 [0.48924357 0.96130683 0.89595925]]
answer 1:  
 [[1.14439164]
 [1.34296276]
 [2.34650965]]
answer 2:  
 [[1.14439164]
 [1.34296276]
 [2.34650965]]
answer 3:  
 [[1.14439164]
 [1.34296276]
 [2.34650965]]


In [87]:
print('''\n17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.''')
a = np.random.randint(1, 11, size=(3, 4))
print(f"a: \n{a}")
b = np.square(a)
print("answer:  \n", b)
c = a * a
print("answer 2:  \n", c)
d = a ** 2
print("answer 3:  \n", d)


17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
a: 
[[4 8 8 1]
 [7 9 1 3]
 [7 5 9 5]]
answer:  
 [[16 64 64  1]
 [49 81  1  9]
 [49 25 81 25]]
answer 2:  
 [[16 64 64  1]
 [49 81  1  9]
 [49 25 81 25]]
answer 3:  
 [[16 64 64  1]
 [49 81  1  9]
 [49 25 81 25]]


In [89]:
print('''\n18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.''')
a = np.random.randint(1, 51, size=4)
print(f"a: \n{a}")
b = a ** 0.5
print("answer:  \n", b)
c = np.sqrt(a)
print("answer 2:  \n", c)


18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
a: 
[47 25 47 34]
answer:  
 [6.8556546  5.         6.8556546  5.83095189]
answer 2:  
 [6.8556546  5.         6.8556546  5.83095189]
